<?php
/**
 * SalesInvoiceApi
 * PHP version 8.1
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orbit Public API
 *
 * The stable, external-integration surface of the Orbit API. Authenticate with an API key (Settings > API Keys) via the X-Api-Key header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KuziumOrbitClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use KuziumOrbitClient\ApiException;
use KuziumOrbitClient\Configuration;
use KuziumOrbitClient\FormDataProcessor;
use KuziumOrbitClient\HeaderSelector;
use KuziumOrbitClient\ObjectSerializer;

/**
 * SalesInvoiceApi Class Doc Comment
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesInvoiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getSalesInvoice' => [
            'application/json',
        ],
        'listSalesInvoicePayments' => [
            'application/json',
        ],
        'listSalesInvoices' => [
            'application/json',
        ],
        'recordSalesInvoicePayment' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSalesInvoice
     *
     * @param  string $account_id account_id (required)
     * @param  string $invoice_id invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSalesInvoice'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KuziumOrbitClient\Model\SalesInvoiceDetailDto
     */
    public function getSalesInvoice($account_id, $invoice_id, string $contentType = self::contentTypes['getSalesInvoice'][0])
    {
        list($response) = $this->getSalesInvoiceWithHttpInfo($account_id, $invoice_id, $contentType);
        return $response;
    }

    /**
     * Operation getSalesInvoiceWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSalesInvoice'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KuziumOrbitClient\Model\SalesInvoiceDetailDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSalesInvoiceWithHttpInfo($account_id, $invoice_id, string $contentType = self::contentTypes['getSalesInvoice'][0])
    {
        $request = $this->getSalesInvoiceRequest($account_id, $invoice_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KuziumOrbitClient\Model\SalesInvoiceDetailDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KuziumOrbitClient\Model\SalesInvoiceDetailDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KuziumOrbitClient\Model\SalesInvoiceDetailDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getSalesInvoiceAsync
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSalesInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSalesInvoiceAsync($account_id, $invoice_id, string $contentType = self::contentTypes['getSalesInvoice'][0])
    {
        return $this->getSalesInvoiceAsyncWithHttpInfo($account_id, $invoice_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSalesInvoiceAsyncWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSalesInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSalesInvoiceAsyncWithHttpInfo($account_id, $invoice_id, string $contentType = self::contentTypes['getSalesInvoice'][0])
    {
        $returnType = '\KuziumOrbitClient\Model\SalesInvoiceDetailDto';
        $request = $this->getSalesInvoiceRequest($account_id, $invoice_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSalesInvoice'
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSalesInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSalesInvoiceRequest($account_id, $invoice_id, string $contentType = self::contentTypes['getSalesInvoice'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getSalesInvoice'
            );
        }

        // verify the required parameter 'invoice_id' is set
        if ($invoice_id === null || (is_array($invoice_id) && count($invoice_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_id when calling getSalesInvoice'
            );
        }


        $resourcePath = '/api/v1/accounts/{accountId}/sales/invoices/{invoiceId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{accountId}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($invoice_id !== null) {
            $resourcePath = str_replace(
                '{invoiceId}',
                ObjectSerializer::toPathValue($invoice_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listSalesInvoicePayments
     *
     * @param  string $account_id account_id (required)
     * @param  string $invoice_id invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoicePayments'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KuziumOrbitClient\Model\SalesInvoicePaymentDto[]
     */
    public function listSalesInvoicePayments($account_id, $invoice_id, string $contentType = self::contentTypes['listSalesInvoicePayments'][0])
    {
        list($response) = $this->listSalesInvoicePaymentsWithHttpInfo($account_id, $invoice_id, $contentType);
        return $response;
    }

    /**
     * Operation listSalesInvoicePaymentsWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoicePayments'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KuziumOrbitClient\Model\SalesInvoicePaymentDto[], HTTP status code, HTTP response headers (array of strings)
     */
    public function listSalesInvoicePaymentsWithHttpInfo($account_id, $invoice_id, string $contentType = self::contentTypes['listSalesInvoicePayments'][0])
    {
        $request = $this->listSalesInvoicePaymentsRequest($account_id, $invoice_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KuziumOrbitClient\Model\SalesInvoicePaymentDto[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KuziumOrbitClient\Model\SalesInvoicePaymentDto[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KuziumOrbitClient\Model\SalesInvoicePaymentDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listSalesInvoicePaymentsAsync
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoicePayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSalesInvoicePaymentsAsync($account_id, $invoice_id, string $contentType = self::contentTypes['listSalesInvoicePayments'][0])
    {
        return $this->listSalesInvoicePaymentsAsyncWithHttpInfo($account_id, $invoice_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listSalesInvoicePaymentsAsyncWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoicePayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSalesInvoicePaymentsAsyncWithHttpInfo($account_id, $invoice_id, string $contentType = self::contentTypes['listSalesInvoicePayments'][0])
    {
        $returnType = '\KuziumOrbitClient\Model\SalesInvoicePaymentDto[]';
        $request = $this->listSalesInvoicePaymentsRequest($account_id, $invoice_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listSalesInvoicePayments'
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoicePayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSalesInvoicePaymentsRequest($account_id, $invoice_id, string $contentType = self::contentTypes['listSalesInvoicePayments'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling listSalesInvoicePayments'
            );
        }

        // verify the required parameter 'invoice_id' is set
        if ($invoice_id === null || (is_array($invoice_id) && count($invoice_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_id when calling listSalesInvoicePayments'
            );
        }


        $resourcePath = '/api/v1/accounts/{accountId}/sales/invoices/{invoiceId}/payments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{accountId}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($invoice_id !== null) {
            $resourcePath = str_replace(
                '{invoiceId}',
                ObjectSerializer::toPathValue($invoice_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listSalesInvoices
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $customer_id customer_id (optional)
     * @param  string|null $status status (optional)
     * @param  string|null $search search (optional)
     * @param  string|null $filter filter (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $page_size page_size (optional, default to 0)
     * @param  string|null $sort_by sort_by (optional, default to 'invoicedate')
     * @param  string|null $sort_order sort_order (optional, default to 'desc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoices'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KuziumOrbitClient\Model\PagedResultOfSalesInvoiceDto
     */
    public function listSalesInvoices($account_id, $customer_id = null, $status = null, $search = null, $filter = null, $page = 1, $page_size = 0, $sort_by = 'invoicedate', $sort_order = 'desc', string $contentType = self::contentTypes['listSalesInvoices'][0])
    {
        list($response) = $this->listSalesInvoicesWithHttpInfo($account_id, $customer_id, $status, $search, $filter, $page, $page_size, $sort_by, $sort_order, $contentType);
        return $response;
    }

    /**
     * Operation listSalesInvoicesWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string|null $customer_id (optional)
     * @param  string|null $status (optional)
     * @param  string|null $search (optional)
     * @param  string|null $filter (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 0)
     * @param  string|null $sort_by (optional, default to 'invoicedate')
     * @param  string|null $sort_order (optional, default to 'desc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoices'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KuziumOrbitClient\Model\PagedResultOfSalesInvoiceDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSalesInvoicesWithHttpInfo($account_id, $customer_id = null, $status = null, $search = null, $filter = null, $page = 1, $page_size = 0, $sort_by = 'invoicedate', $sort_order = 'desc', string $contentType = self::contentTypes['listSalesInvoices'][0])
    {
        $request = $this->listSalesInvoicesRequest($account_id, $customer_id, $status, $search, $filter, $page, $page_size, $sort_by, $sort_order, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KuziumOrbitClient\Model\PagedResultOfSalesInvoiceDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KuziumOrbitClient\Model\PagedResultOfSalesInvoiceDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KuziumOrbitClient\Model\PagedResultOfSalesInvoiceDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listSalesInvoicesAsync
     *
     * @param  string $account_id (required)
     * @param  string|null $customer_id (optional)
     * @param  string|null $status (optional)
     * @param  string|null $search (optional)
     * @param  string|null $filter (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 0)
     * @param  string|null $sort_by (optional, default to 'invoicedate')
     * @param  string|null $sort_order (optional, default to 'desc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSalesInvoicesAsync($account_id, $customer_id = null, $status = null, $search = null, $filter = null, $page = 1, $page_size = 0, $sort_by = 'invoicedate', $sort_order = 'desc', string $contentType = self::contentTypes['listSalesInvoices'][0])
    {
        return $this->listSalesInvoicesAsyncWithHttpInfo($account_id, $customer_id, $status, $search, $filter, $page, $page_size, $sort_by, $sort_order, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listSalesInvoicesAsyncWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string|null $customer_id (optional)
     * @param  string|null $status (optional)
     * @param  string|null $search (optional)
     * @param  string|null $filter (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 0)
     * @param  string|null $sort_by (optional, default to 'invoicedate')
     * @param  string|null $sort_order (optional, default to 'desc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSalesInvoicesAsyncWithHttpInfo($account_id, $customer_id = null, $status = null, $search = null, $filter = null, $page = 1, $page_size = 0, $sort_by = 'invoicedate', $sort_order = 'desc', string $contentType = self::contentTypes['listSalesInvoices'][0])
    {
        $returnType = '\KuziumOrbitClient\Model\PagedResultOfSalesInvoiceDto';
        $request = $this->listSalesInvoicesRequest($account_id, $customer_id, $status, $search, $filter, $page, $page_size, $sort_by, $sort_order, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listSalesInvoices'
     *
     * @param  string $account_id (required)
     * @param  string|null $customer_id (optional)
     * @param  string|null $status (optional)
     * @param  string|null $search (optional)
     * @param  string|null $filter (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 0)
     * @param  string|null $sort_by (optional, default to 'invoicedate')
     * @param  string|null $sort_order (optional, default to 'desc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSalesInvoices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSalesInvoicesRequest($account_id, $customer_id = null, $status = null, $search = null, $filter = null, $page = 1, $page_size = 0, $sort_by = 'invoicedate', $sort_order = 'desc', string $contentType = self::contentTypes['listSalesInvoices'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling listSalesInvoices'
            );
        }










        $resourcePath = '/api/v1/accounts/{accountId}/sales/invoices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customer_id,
            'customerId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            'filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sortBy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_order,
            'sortOrder', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{accountId}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation recordSalesInvoicePayment
     *
     * @param  string $account_id account_id (required)
     * @param  string $invoice_id invoice_id (required)
     * @param  \KuziumOrbitClient\Model\RecordInvoicePaymentRequest $record_invoice_payment_request record_invoice_payment_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordSalesInvoicePayment'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KuziumOrbitClient\Model\SalesInvoicePaymentDto
     */
    public function recordSalesInvoicePayment($account_id, $invoice_id, $record_invoice_payment_request, string $contentType = self::contentTypes['recordSalesInvoicePayment'][0])
    {
        list($response) = $this->recordSalesInvoicePaymentWithHttpInfo($account_id, $invoice_id, $record_invoice_payment_request, $contentType);
        return $response;
    }

    /**
     * Operation recordSalesInvoicePaymentWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  \KuziumOrbitClient\Model\RecordInvoicePaymentRequest $record_invoice_payment_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordSalesInvoicePayment'] to see the possible values for this operation
     *
     * @throws \KuziumOrbitClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KuziumOrbitClient\Model\SalesInvoicePaymentDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function recordSalesInvoicePaymentWithHttpInfo($account_id, $invoice_id, $record_invoice_payment_request, string $contentType = self::contentTypes['recordSalesInvoicePayment'][0])
    {
        $request = $this->recordSalesInvoicePaymentRequest($account_id, $invoice_id, $record_invoice_payment_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KuziumOrbitClient\Model\SalesInvoicePaymentDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KuziumOrbitClient\Model\SalesInvoicePaymentDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KuziumOrbitClient\Model\SalesInvoicePaymentDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation recordSalesInvoicePaymentAsync
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  \KuziumOrbitClient\Model\RecordInvoicePaymentRequest $record_invoice_payment_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordSalesInvoicePayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recordSalesInvoicePaymentAsync($account_id, $invoice_id, $record_invoice_payment_request, string $contentType = self::contentTypes['recordSalesInvoicePayment'][0])
    {
        return $this->recordSalesInvoicePaymentAsyncWithHttpInfo($account_id, $invoice_id, $record_invoice_payment_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation recordSalesInvoicePaymentAsyncWithHttpInfo
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  \KuziumOrbitClient\Model\RecordInvoicePaymentRequest $record_invoice_payment_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordSalesInvoicePayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recordSalesInvoicePaymentAsyncWithHttpInfo($account_id, $invoice_id, $record_invoice_payment_request, string $contentType = self::contentTypes['recordSalesInvoicePayment'][0])
    {
        $returnType = '\KuziumOrbitClient\Model\SalesInvoicePaymentDto';
        $request = $this->recordSalesInvoicePaymentRequest($account_id, $invoice_id, $record_invoice_payment_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'recordSalesInvoicePayment'
     *
     * @param  string $account_id (required)
     * @param  string $invoice_id (required)
     * @param  \KuziumOrbitClient\Model\RecordInvoicePaymentRequest $record_invoice_payment_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordSalesInvoicePayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function recordSalesInvoicePaymentRequest($account_id, $invoice_id, $record_invoice_payment_request, string $contentType = self::contentTypes['recordSalesInvoicePayment'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling recordSalesInvoicePayment'
            );
        }

        // verify the required parameter 'invoice_id' is set
        if ($invoice_id === null || (is_array($invoice_id) && count($invoice_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_id when calling recordSalesInvoicePayment'
            );
        }

        // verify the required parameter 'record_invoice_payment_request' is set
        if ($record_invoice_payment_request === null || (is_array($record_invoice_payment_request) && count($record_invoice_payment_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_invoice_payment_request when calling recordSalesInvoicePayment'
            );
        }


        $resourcePath = '/api/v1/accounts/{accountId}/sales/invoices/{invoiceId}/payments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{accountId}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($invoice_id !== null) {
            $resourcePath = str_replace(
                '{invoiceId}',
                ObjectSerializer::toPathValue($invoice_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($record_invoice_payment_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($record_invoice_payment_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $record_invoice_payment_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
