<?php
/**
 * CreatePaymentReceiptRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orbit Public API
 *
 * The stable, external-integration surface of the Orbit API. Authenticate with an API key (Settings > API Keys) via the X-Api-Key header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KuziumOrbitClient\Model;

use \ArrayAccess;
use \KuziumOrbitClient\ObjectSerializer;

/**
 * CreatePaymentReceiptRequest Class Doc Comment
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreatePaymentReceiptRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CreatePaymentReceiptRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'voucher_type' => 'string',
        'posting_date' => 'string',
        'external_reference_no' => 'string',
        'debit_account_id' => 'string',
        'credit_account_id' => 'string',
        'amount' => 'float',
        'is_tax_inclusive' => 'bool',
        'tax_rate_id' => 'string',
        'tax_account_id' => 'string',
        'currency_code' => 'string',
        'foreign_amount' => 'float',
        'exchange_rate' => 'float',
        'description' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'voucher_type' => null,
        'posting_date' => null,
        'external_reference_no' => null,
        'debit_account_id' => 'uuid',
        'credit_account_id' => 'uuid',
        'amount' => 'double',
        'is_tax_inclusive' => null,
        'tax_rate_id' => 'uuid',
        'tax_account_id' => 'uuid',
        'currency_code' => null,
        'foreign_amount' => 'double',
        'exchange_rate' => 'double',
        'description' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'voucher_type' => false,
        'posting_date' => true,
        'external_reference_no' => true,
        'debit_account_id' => false,
        'credit_account_id' => false,
        'amount' => false,
        'is_tax_inclusive' => false,
        'tax_rate_id' => true,
        'tax_account_id' => true,
        'currency_code' => true,
        'foreign_amount' => false,
        'exchange_rate' => false,
        'description' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'voucher_type' => 'voucherType',
        'posting_date' => 'postingDate',
        'external_reference_no' => 'externalReferenceNo',
        'debit_account_id' => 'debitAccountId',
        'credit_account_id' => 'creditAccountId',
        'amount' => 'amount',
        'is_tax_inclusive' => 'isTaxInclusive',
        'tax_rate_id' => 'taxRateId',
        'tax_account_id' => 'taxAccountId',
        'currency_code' => 'currencyCode',
        'foreign_amount' => 'foreignAmount',
        'exchange_rate' => 'exchangeRate',
        'description' => 'description'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'voucher_type' => 'setVoucherType',
        'posting_date' => 'setPostingDate',
        'external_reference_no' => 'setExternalReferenceNo',
        'debit_account_id' => 'setDebitAccountId',
        'credit_account_id' => 'setCreditAccountId',
        'amount' => 'setAmount',
        'is_tax_inclusive' => 'setIsTaxInclusive',
        'tax_rate_id' => 'setTaxRateId',
        'tax_account_id' => 'setTaxAccountId',
        'currency_code' => 'setCurrencyCode',
        'foreign_amount' => 'setForeignAmount',
        'exchange_rate' => 'setExchangeRate',
        'description' => 'setDescription'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'voucher_type' => 'getVoucherType',
        'posting_date' => 'getPostingDate',
        'external_reference_no' => 'getExternalReferenceNo',
        'debit_account_id' => 'getDebitAccountId',
        'credit_account_id' => 'getCreditAccountId',
        'amount' => 'getAmount',
        'is_tax_inclusive' => 'getIsTaxInclusive',
        'tax_rate_id' => 'getTaxRateId',
        'tax_account_id' => 'getTaxAccountId',
        'currency_code' => 'getCurrencyCode',
        'foreign_amount' => 'getForeignAmount',
        'exchange_rate' => 'getExchangeRate',
        'description' => 'getDescription'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('voucher_type', $data ?? [], null);
        $this->setIfExists('posting_date', $data ?? [], null);
        $this->setIfExists('external_reference_no', $data ?? [], null);
        $this->setIfExists('debit_account_id', $data ?? [], null);
        $this->setIfExists('credit_account_id', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('is_tax_inclusive', $data ?? [], null);
        $this->setIfExists('tax_rate_id', $data ?? [], null);
        $this->setIfExists('tax_account_id', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('foreign_amount', $data ?? [], null);
        $this->setIfExists('exchange_rate', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['voucher_type'] === null) {
            $invalidProperties[] = "'voucher_type' can't be null";
        }
        if ($this->container['posting_date'] === null && !$this->isNullableSetToNull('posting_date')) {
            $invalidProperties[] = "'posting_date' is required";
        }
        if ($this->container['external_reference_no'] === null && !$this->isNullableSetToNull('external_reference_no')) {
            $invalidProperties[] = "'external_reference_no' is required";
        }
        if ($this->container['debit_account_id'] === null) {
            $invalidProperties[] = "'debit_account_id' can't be null";
        }
        if ($this->container['credit_account_id'] === null) {
            $invalidProperties[] = "'credit_account_id' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['is_tax_inclusive'] === null) {
            $invalidProperties[] = "'is_tax_inclusive' can't be null";
        }
        if ($this->container['tax_rate_id'] === null && !$this->isNullableSetToNull('tax_rate_id')) {
            $invalidProperties[] = "'tax_rate_id' is required";
        }
        if ($this->container['tax_account_id'] === null && !$this->isNullableSetToNull('tax_account_id')) {
            $invalidProperties[] = "'tax_account_id' is required";
        }
        if ($this->container['currency_code'] === null && !$this->isNullableSetToNull('currency_code')) {
            $invalidProperties[] = "'currency_code' is required";
        }
        if ($this->container['foreign_amount'] === null) {
            $invalidProperties[] = "'foreign_amount' can't be null";
        }
        if ($this->container['exchange_rate'] === null) {
            $invalidProperties[] = "'exchange_rate' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets voucher_type
     *
     * @return string
     */
    public function getVoucherType()
    {
        return $this->container['voucher_type'];
    }

    /**
     * Sets voucher_type
     *
     * @param string $voucher_type voucher_type
     *
     * @return self
     */
    public function setVoucherType($voucher_type)
    {
        if (is_null($voucher_type)) {
            throw new \InvalidArgumentException('non-nullable voucher_type cannot be null');
        }
        $this->container['voucher_type'] = $voucher_type;

        return $this;
    }

    /**
     * Gets posting_date
     *
     * @return string|null
     */
    public function getPostingDate()
    {
        return $this->container['posting_date'];
    }

    /**
     * Sets posting_date
     *
     * @param string|null $posting_date posting_date
     *
     * @return self
     */
    public function setPostingDate($posting_date)
    {
        if (is_null($posting_date)) {
            array_push($this->openAPINullablesSetToNull, 'posting_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('posting_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['posting_date'] = $posting_date;

        return $this;
    }

    /**
     * Gets external_reference_no
     *
     * @return string|null
     */
    public function getExternalReferenceNo()
    {
        return $this->container['external_reference_no'];
    }

    /**
     * Sets external_reference_no
     *
     * @param string|null $external_reference_no external_reference_no
     *
     * @return self
     */
    public function setExternalReferenceNo($external_reference_no)
    {
        if (is_null($external_reference_no)) {
            array_push($this->openAPINullablesSetToNull, 'external_reference_no');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_reference_no', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_reference_no'] = $external_reference_no;

        return $this;
    }

    /**
     * Gets debit_account_id
     *
     * @return string
     */
    public function getDebitAccountId()
    {
        return $this->container['debit_account_id'];
    }

    /**
     * Sets debit_account_id
     *
     * @param string $debit_account_id debit_account_id
     *
     * @return self
     */
    public function setDebitAccountId($debit_account_id)
    {
        if (is_null($debit_account_id)) {
            throw new \InvalidArgumentException('non-nullable debit_account_id cannot be null');
        }
        $this->container['debit_account_id'] = $debit_account_id;

        return $this;
    }

    /**
     * Gets credit_account_id
     *
     * @return string
     */
    public function getCreditAccountId()
    {
        return $this->container['credit_account_id'];
    }

    /**
     * Sets credit_account_id
     *
     * @param string $credit_account_id credit_account_id
     *
     * @return self
     */
    public function setCreditAccountId($credit_account_id)
    {
        if (is_null($credit_account_id)) {
            throw new \InvalidArgumentException('non-nullable credit_account_id cannot be null');
        }
        $this->container['credit_account_id'] = $credit_account_id;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets is_tax_inclusive
     *
     * @return bool
     */
    public function getIsTaxInclusive()
    {
        return $this->container['is_tax_inclusive'];
    }

    /**
     * Sets is_tax_inclusive
     *
     * @param bool $is_tax_inclusive is_tax_inclusive
     *
     * @return self
     */
    public function setIsTaxInclusive($is_tax_inclusive)
    {
        if (is_null($is_tax_inclusive)) {
            throw new \InvalidArgumentException('non-nullable is_tax_inclusive cannot be null');
        }
        $this->container['is_tax_inclusive'] = $is_tax_inclusive;

        return $this;
    }

    /**
     * Gets tax_rate_id
     *
     * @return string|null
     */
    public function getTaxRateId()
    {
        return $this->container['tax_rate_id'];
    }

    /**
     * Sets tax_rate_id
     *
     * @param string|null $tax_rate_id tax_rate_id
     *
     * @return self
     */
    public function setTaxRateId($tax_rate_id)
    {
        if (is_null($tax_rate_id)) {
            array_push($this->openAPINullablesSetToNull, 'tax_rate_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tax_rate_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tax_rate_id'] = $tax_rate_id;

        return $this;
    }

    /**
     * Gets tax_account_id
     *
     * @return string|null
     */
    public function getTaxAccountId()
    {
        return $this->container['tax_account_id'];
    }

    /**
     * Sets tax_account_id
     *
     * @param string|null $tax_account_id tax_account_id
     *
     * @return self
     */
    public function setTaxAccountId($tax_account_id)
    {
        if (is_null($tax_account_id)) {
            array_push($this->openAPINullablesSetToNull, 'tax_account_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tax_account_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tax_account_id'] = $tax_account_id;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code currency_code
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        if (is_null($currency_code)) {
            array_push($this->openAPINullablesSetToNull, 'currency_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('currency_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets foreign_amount
     *
     * @return float
     */
    public function getForeignAmount()
    {
        return $this->container['foreign_amount'];
    }

    /**
     * Sets foreign_amount
     *
     * @param float $foreign_amount foreign_amount
     *
     * @return self
     */
    public function setForeignAmount($foreign_amount)
    {
        if (is_null($foreign_amount)) {
            throw new \InvalidArgumentException('non-nullable foreign_amount cannot be null');
        }
        $this->container['foreign_amount'] = $foreign_amount;

        return $this;
    }

    /**
     * Gets exchange_rate
     *
     * @return float
     */
    public function getExchangeRate()
    {
        return $this->container['exchange_rate'];
    }

    /**
     * Sets exchange_rate
     *
     * @param float $exchange_rate exchange_rate
     *
     * @return self
     */
    public function setExchangeRate($exchange_rate)
    {
        if (is_null($exchange_rate)) {
            throw new \InvalidArgumentException('non-nullable exchange_rate cannot be null');
        }
        $this->container['exchange_rate'] = $exchange_rate;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


