<?php
/**
 * ProductResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orbit Public API
 *
 * The stable, external-integration surface of the Orbit API. Authenticate with an API key (Settings > API Keys) via the X-Api-Key header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KuziumOrbitClient\Model;

use \ArrayAccess;
use \KuziumOrbitClient\ObjectSerializer;

/**
 * ProductResponse Class Doc Comment
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProductResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ProductResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'account_id' => 'string',
        'sku' => 'string',
        'name' => 'string',
        'description' => 'string',
        'barcode' => 'string',
        'product_type' => 'int',
        'category_id' => 'string',
        'category_name' => 'string',
        'unit_of_measure_id' => 'string',
        'unit_of_measure_name' => 'string',
        'unit_of_measure_symbol' => 'string',
        'cost_price' => 'float',
        'unit_price' => 'float',
        'tax_rate' => 'float',
        'tax_rate_id' => 'string',
        'track_inventory' => 'bool',
        'reorder_level' => 'float',
        'min_stock_level' => 'float',
        'max_stock_level' => 'float',
        'tracks_lot' => 'bool',
        'tracks_serial' => 'bool',
        'costing_method' => 'int',
        'average_cost' => 'float',
        'image_url' => 'string',
        'is_active' => 'bool',
        'display_order' => 'int',
        'parent_product_id' => 'string',
        'variant_attributes' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'account_id' => 'uuid',
        'sku' => null,
        'name' => null,
        'description' => null,
        'barcode' => null,
        'product_type' => null,
        'category_id' => 'uuid',
        'category_name' => null,
        'unit_of_measure_id' => 'uuid',
        'unit_of_measure_name' => null,
        'unit_of_measure_symbol' => null,
        'cost_price' => 'double',
        'unit_price' => 'double',
        'tax_rate' => 'double',
        'tax_rate_id' => 'uuid',
        'track_inventory' => null,
        'reorder_level' => 'double',
        'min_stock_level' => 'double',
        'max_stock_level' => 'double',
        'tracks_lot' => null,
        'tracks_serial' => null,
        'costing_method' => null,
        'average_cost' => 'double',
        'image_url' => null,
        'is_active' => null,
        'display_order' => 'int32',
        'parent_product_id' => 'uuid',
        'variant_attributes' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'account_id' => false,
        'sku' => false,
        'name' => false,
        'description' => true,
        'barcode' => true,
        'product_type' => false,
        'category_id' => true,
        'category_name' => true,
        'unit_of_measure_id' => false,
        'unit_of_measure_name' => true,
        'unit_of_measure_symbol' => true,
        'cost_price' => false,
        'unit_price' => false,
        'tax_rate' => false,
        'tax_rate_id' => true,
        'track_inventory' => false,
        'reorder_level' => false,
        'min_stock_level' => false,
        'max_stock_level' => false,
        'tracks_lot' => false,
        'tracks_serial' => false,
        'costing_method' => false,
        'average_cost' => false,
        'image_url' => true,
        'is_active' => false,
        'display_order' => false,
        'parent_product_id' => true,
        'variant_attributes' => true,
        'created_at' => false,
        'updated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'account_id' => 'accountId',
        'sku' => 'sku',
        'name' => 'name',
        'description' => 'description',
        'barcode' => 'barcode',
        'product_type' => 'productType',
        'category_id' => 'categoryId',
        'category_name' => 'categoryName',
        'unit_of_measure_id' => 'unitOfMeasureId',
        'unit_of_measure_name' => 'unitOfMeasureName',
        'unit_of_measure_symbol' => 'unitOfMeasureSymbol',
        'cost_price' => 'costPrice',
        'unit_price' => 'unitPrice',
        'tax_rate' => 'taxRate',
        'tax_rate_id' => 'taxRateId',
        'track_inventory' => 'trackInventory',
        'reorder_level' => 'reorderLevel',
        'min_stock_level' => 'minStockLevel',
        'max_stock_level' => 'maxStockLevel',
        'tracks_lot' => 'tracksLot',
        'tracks_serial' => 'tracksSerial',
        'costing_method' => 'costingMethod',
        'average_cost' => 'averageCost',
        'image_url' => 'imageUrl',
        'is_active' => 'isActive',
        'display_order' => 'displayOrder',
        'parent_product_id' => 'parentProductId',
        'variant_attributes' => 'variantAttributes',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'account_id' => 'setAccountId',
        'sku' => 'setSku',
        'name' => 'setName',
        'description' => 'setDescription',
        'barcode' => 'setBarcode',
        'product_type' => 'setProductType',
        'category_id' => 'setCategoryId',
        'category_name' => 'setCategoryName',
        'unit_of_measure_id' => 'setUnitOfMeasureId',
        'unit_of_measure_name' => 'setUnitOfMeasureName',
        'unit_of_measure_symbol' => 'setUnitOfMeasureSymbol',
        'cost_price' => 'setCostPrice',
        'unit_price' => 'setUnitPrice',
        'tax_rate' => 'setTaxRate',
        'tax_rate_id' => 'setTaxRateId',
        'track_inventory' => 'setTrackInventory',
        'reorder_level' => 'setReorderLevel',
        'min_stock_level' => 'setMinStockLevel',
        'max_stock_level' => 'setMaxStockLevel',
        'tracks_lot' => 'setTracksLot',
        'tracks_serial' => 'setTracksSerial',
        'costing_method' => 'setCostingMethod',
        'average_cost' => 'setAverageCost',
        'image_url' => 'setImageUrl',
        'is_active' => 'setIsActive',
        'display_order' => 'setDisplayOrder',
        'parent_product_id' => 'setParentProductId',
        'variant_attributes' => 'setVariantAttributes',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'account_id' => 'getAccountId',
        'sku' => 'getSku',
        'name' => 'getName',
        'description' => 'getDescription',
        'barcode' => 'getBarcode',
        'product_type' => 'getProductType',
        'category_id' => 'getCategoryId',
        'category_name' => 'getCategoryName',
        'unit_of_measure_id' => 'getUnitOfMeasureId',
        'unit_of_measure_name' => 'getUnitOfMeasureName',
        'unit_of_measure_symbol' => 'getUnitOfMeasureSymbol',
        'cost_price' => 'getCostPrice',
        'unit_price' => 'getUnitPrice',
        'tax_rate' => 'getTaxRate',
        'tax_rate_id' => 'getTaxRateId',
        'track_inventory' => 'getTrackInventory',
        'reorder_level' => 'getReorderLevel',
        'min_stock_level' => 'getMinStockLevel',
        'max_stock_level' => 'getMaxStockLevel',
        'tracks_lot' => 'getTracksLot',
        'tracks_serial' => 'getTracksSerial',
        'costing_method' => 'getCostingMethod',
        'average_cost' => 'getAverageCost',
        'image_url' => 'getImageUrl',
        'is_active' => 'getIsActive',
        'display_order' => 'getDisplayOrder',
        'parent_product_id' => 'getParentProductId',
        'variant_attributes' => 'getVariantAttributes',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('sku', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('barcode', $data ?? [], null);
        $this->setIfExists('product_type', $data ?? [], null);
        $this->setIfExists('category_id', $data ?? [], null);
        $this->setIfExists('category_name', $data ?? [], null);
        $this->setIfExists('unit_of_measure_id', $data ?? [], null);
        $this->setIfExists('unit_of_measure_name', $data ?? [], null);
        $this->setIfExists('unit_of_measure_symbol', $data ?? [], null);
        $this->setIfExists('cost_price', $data ?? [], null);
        $this->setIfExists('unit_price', $data ?? [], null);
        $this->setIfExists('tax_rate', $data ?? [], null);
        $this->setIfExists('tax_rate_id', $data ?? [], null);
        $this->setIfExists('track_inventory', $data ?? [], null);
        $this->setIfExists('reorder_level', $data ?? [], null);
        $this->setIfExists('min_stock_level', $data ?? [], null);
        $this->setIfExists('max_stock_level', $data ?? [], null);
        $this->setIfExists('tracks_lot', $data ?? [], null);
        $this->setIfExists('tracks_serial', $data ?? [], null);
        $this->setIfExists('costing_method', $data ?? [], null);
        $this->setIfExists('average_cost', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('display_order', $data ?? [], null);
        $this->setIfExists('parent_product_id', $data ?? [], null);
        $this->setIfExists('variant_attributes', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if ($this->container['sku'] === null) {
            $invalidProperties[] = "'sku' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['product_type'] === null) {
            $invalidProperties[] = "'product_type' can't be null";
        }
        if ($this->container['unit_of_measure_id'] === null) {
            $invalidProperties[] = "'unit_of_measure_id' can't be null";
        }
        if ($this->container['cost_price'] === null) {
            $invalidProperties[] = "'cost_price' can't be null";
        }
        if ($this->container['unit_price'] === null) {
            $invalidProperties[] = "'unit_price' can't be null";
        }
        if ($this->container['track_inventory'] === null) {
            $invalidProperties[] = "'track_inventory' can't be null";
        }
        if ($this->container['is_active'] === null) {
            $invalidProperties[] = "'is_active' can't be null";
        }
        if ($this->container['display_order'] === null) {
            $invalidProperties[] = "'display_order' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string $sku sku
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets barcode
     *
     * @return string|null
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     *
     * @param string|null $barcode barcode
     *
     * @return self
     */
    public function setBarcode($barcode)
    {
        if (is_null($barcode)) {
            array_push($this->openAPINullablesSetToNull, 'barcode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('barcode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets product_type
     *
     * @return int
     */
    public function getProductType()
    {
        return $this->container['product_type'];
    }

    /**
     * Sets product_type
     *
     * @param int $product_type product_type
     *
     * @return self
     */
    public function setProductType($product_type)
    {
        if (is_null($product_type)) {
            throw new \InvalidArgumentException('non-nullable product_type cannot be null');
        }
        $this->container['product_type'] = $product_type;

        return $this;
    }

    /**
     * Gets category_id
     *
     * @return string|null
     */
    public function getCategoryId()
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     *
     * @param string|null $category_id category_id
     *
     * @return self
     */
    public function setCategoryId($category_id)
    {
        if (is_null($category_id)) {
            array_push($this->openAPINullablesSetToNull, 'category_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('category_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets category_name
     *
     * @return string|null
     */
    public function getCategoryName()
    {
        return $this->container['category_name'];
    }

    /**
     * Sets category_name
     *
     * @param string|null $category_name category_name
     *
     * @return self
     */
    public function setCategoryName($category_name)
    {
        if (is_null($category_name)) {
            array_push($this->openAPINullablesSetToNull, 'category_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('category_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['category_name'] = $category_name;

        return $this;
    }

    /**
     * Gets unit_of_measure_id
     *
     * @return string
     */
    public function getUnitOfMeasureId()
    {
        return $this->container['unit_of_measure_id'];
    }

    /**
     * Sets unit_of_measure_id
     *
     * @param string $unit_of_measure_id unit_of_measure_id
     *
     * @return self
     */
    public function setUnitOfMeasureId($unit_of_measure_id)
    {
        if (is_null($unit_of_measure_id)) {
            throw new \InvalidArgumentException('non-nullable unit_of_measure_id cannot be null');
        }
        $this->container['unit_of_measure_id'] = $unit_of_measure_id;

        return $this;
    }

    /**
     * Gets unit_of_measure_name
     *
     * @return string|null
     */
    public function getUnitOfMeasureName()
    {
        return $this->container['unit_of_measure_name'];
    }

    /**
     * Sets unit_of_measure_name
     *
     * @param string|null $unit_of_measure_name unit_of_measure_name
     *
     * @return self
     */
    public function setUnitOfMeasureName($unit_of_measure_name)
    {
        if (is_null($unit_of_measure_name)) {
            array_push($this->openAPINullablesSetToNull, 'unit_of_measure_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unit_of_measure_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unit_of_measure_name'] = $unit_of_measure_name;

        return $this;
    }

    /**
     * Gets unit_of_measure_symbol
     *
     * @return string|null
     */
    public function getUnitOfMeasureSymbol()
    {
        return $this->container['unit_of_measure_symbol'];
    }

    /**
     * Sets unit_of_measure_symbol
     *
     * @param string|null $unit_of_measure_symbol unit_of_measure_symbol
     *
     * @return self
     */
    public function setUnitOfMeasureSymbol($unit_of_measure_symbol)
    {
        if (is_null($unit_of_measure_symbol)) {
            array_push($this->openAPINullablesSetToNull, 'unit_of_measure_symbol');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unit_of_measure_symbol', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unit_of_measure_symbol'] = $unit_of_measure_symbol;

        return $this;
    }

    /**
     * Gets cost_price
     *
     * @return float
     */
    public function getCostPrice()
    {
        return $this->container['cost_price'];
    }

    /**
     * Sets cost_price
     *
     * @param float $cost_price cost_price
     *
     * @return self
     */
    public function setCostPrice($cost_price)
    {
        if (is_null($cost_price)) {
            throw new \InvalidArgumentException('non-nullable cost_price cannot be null');
        }
        $this->container['cost_price'] = $cost_price;

        return $this;
    }

    /**
     * Gets unit_price
     *
     * @return float
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     *
     * @param float $unit_price unit_price
     *
     * @return self
     */
    public function setUnitPrice($unit_price)
    {
        if (is_null($unit_price)) {
            throw new \InvalidArgumentException('non-nullable unit_price cannot be null');
        }
        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets tax_rate
     *
     * @return float|null
     */
    public function getTaxRate()
    {
        return $this->container['tax_rate'];
    }

    /**
     * Sets tax_rate
     *
     * @param float|null $tax_rate tax_rate
     *
     * @return self
     */
    public function setTaxRate($tax_rate)
    {
        if (is_null($tax_rate)) {
            throw new \InvalidArgumentException('non-nullable tax_rate cannot be null');
        }
        $this->container['tax_rate'] = $tax_rate;

        return $this;
    }

    /**
     * Gets tax_rate_id
     *
     * @return string|null
     */
    public function getTaxRateId()
    {
        return $this->container['tax_rate_id'];
    }

    /**
     * Sets tax_rate_id
     *
     * @param string|null $tax_rate_id tax_rate_id
     *
     * @return self
     */
    public function setTaxRateId($tax_rate_id)
    {
        if (is_null($tax_rate_id)) {
            array_push($this->openAPINullablesSetToNull, 'tax_rate_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tax_rate_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tax_rate_id'] = $tax_rate_id;

        return $this;
    }

    /**
     * Gets track_inventory
     *
     * @return bool
     */
    public function getTrackInventory()
    {
        return $this->container['track_inventory'];
    }

    /**
     * Sets track_inventory
     *
     * @param bool $track_inventory track_inventory
     *
     * @return self
     */
    public function setTrackInventory($track_inventory)
    {
        if (is_null($track_inventory)) {
            throw new \InvalidArgumentException('non-nullable track_inventory cannot be null');
        }
        $this->container['track_inventory'] = $track_inventory;

        return $this;
    }

    /**
     * Gets reorder_level
     *
     * @return float|null
     */
    public function getReorderLevel()
    {
        return $this->container['reorder_level'];
    }

    /**
     * Sets reorder_level
     *
     * @param float|null $reorder_level reorder_level
     *
     * @return self
     */
    public function setReorderLevel($reorder_level)
    {
        if (is_null($reorder_level)) {
            throw new \InvalidArgumentException('non-nullable reorder_level cannot be null');
        }
        $this->container['reorder_level'] = $reorder_level;

        return $this;
    }

    /**
     * Gets min_stock_level
     *
     * @return float|null
     */
    public function getMinStockLevel()
    {
        return $this->container['min_stock_level'];
    }

    /**
     * Sets min_stock_level
     *
     * @param float|null $min_stock_level min_stock_level
     *
     * @return self
     */
    public function setMinStockLevel($min_stock_level)
    {
        if (is_null($min_stock_level)) {
            throw new \InvalidArgumentException('non-nullable min_stock_level cannot be null');
        }
        $this->container['min_stock_level'] = $min_stock_level;

        return $this;
    }

    /**
     * Gets max_stock_level
     *
     * @return float|null
     */
    public function getMaxStockLevel()
    {
        return $this->container['max_stock_level'];
    }

    /**
     * Sets max_stock_level
     *
     * @param float|null $max_stock_level max_stock_level
     *
     * @return self
     */
    public function setMaxStockLevel($max_stock_level)
    {
        if (is_null($max_stock_level)) {
            throw new \InvalidArgumentException('non-nullable max_stock_level cannot be null');
        }
        $this->container['max_stock_level'] = $max_stock_level;

        return $this;
    }

    /**
     * Gets tracks_lot
     *
     * @return bool|null
     */
    public function getTracksLot()
    {
        return $this->container['tracks_lot'];
    }

    /**
     * Sets tracks_lot
     *
     * @param bool|null $tracks_lot tracks_lot
     *
     * @return self
     */
    public function setTracksLot($tracks_lot)
    {
        if (is_null($tracks_lot)) {
            throw new \InvalidArgumentException('non-nullable tracks_lot cannot be null');
        }
        $this->container['tracks_lot'] = $tracks_lot;

        return $this;
    }

    /**
     * Gets tracks_serial
     *
     * @return bool|null
     */
    public function getTracksSerial()
    {
        return $this->container['tracks_serial'];
    }

    /**
     * Sets tracks_serial
     *
     * @param bool|null $tracks_serial tracks_serial
     *
     * @return self
     */
    public function setTracksSerial($tracks_serial)
    {
        if (is_null($tracks_serial)) {
            throw new \InvalidArgumentException('non-nullable tracks_serial cannot be null');
        }
        $this->container['tracks_serial'] = $tracks_serial;

        return $this;
    }

    /**
     * Gets costing_method
     *
     * @return int|null
     */
    public function getCostingMethod()
    {
        return $this->container['costing_method'];
    }

    /**
     * Sets costing_method
     *
     * @param int|null $costing_method costing_method
     *
     * @return self
     */
    public function setCostingMethod($costing_method)
    {
        if (is_null($costing_method)) {
            throw new \InvalidArgumentException('non-nullable costing_method cannot be null');
        }
        $this->container['costing_method'] = $costing_method;

        return $this;
    }

    /**
     * Gets average_cost
     *
     * @return float|null
     */
    public function getAverageCost()
    {
        return $this->container['average_cost'];
    }

    /**
     * Sets average_cost
     *
     * @param float|null $average_cost average_cost
     *
     * @return self
     */
    public function setAverageCost($average_cost)
    {
        if (is_null($average_cost)) {
            throw new \InvalidArgumentException('non-nullable average_cost cannot be null');
        }
        $this->container['average_cost'] = $average_cost;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool $is_active is_active
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets display_order
     *
     * @return int
     */
    public function getDisplayOrder()
    {
        return $this->container['display_order'];
    }

    /**
     * Sets display_order
     *
     * @param int $display_order display_order
     *
     * @return self
     */
    public function setDisplayOrder($display_order)
    {
        if (is_null($display_order)) {
            throw new \InvalidArgumentException('non-nullable display_order cannot be null');
        }
        $this->container['display_order'] = $display_order;

        return $this;
    }

    /**
     * Gets parent_product_id
     *
     * @return string|null
     */
    public function getParentProductId()
    {
        return $this->container['parent_product_id'];
    }

    /**
     * Sets parent_product_id
     *
     * @param string|null $parent_product_id parent_product_id
     *
     * @return self
     */
    public function setParentProductId($parent_product_id)
    {
        if (is_null($parent_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'parent_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parent_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['parent_product_id'] = $parent_product_id;

        return $this;
    }

    /**
     * Gets variant_attributes
     *
     * @return string|null
     */
    public function getVariantAttributes()
    {
        return $this->container['variant_attributes'];
    }

    /**
     * Sets variant_attributes
     *
     * @param string|null $variant_attributes variant_attributes
     *
     * @return self
     */
    public function setVariantAttributes($variant_attributes)
    {
        if (is_null($variant_attributes)) {
            array_push($this->openAPINullablesSetToNull, 'variant_attributes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('variant_attributes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['variant_attributes'] = $variant_attributes;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


