<?php
/**
 * PurchaseApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orbit Public API
 *
 * The stable, external-integration surface of the Orbit API. Authenticate with an API key (Settings > API Keys) via the X-Api-Key header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KuziumOrbitClient\Test\Api;

use \KuziumOrbitClient\Configuration;
use \KuziumOrbitClient\ApiException;
use \KuziumOrbitClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PurchaseApiTest Class Doc Comment
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPurchaseOrder
     *
     * .
     *
     */
    public function testCreatePurchaseOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePurchaseOrder
     *
     * .
     *
     */
    public function testDeletePurchaseOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPurchaseOrder
     *
     * .
     *
     */
    public function testGetPurchaseOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPurchaseOrders
     *
     * .
     *
     */
    public function testListPurchaseOrders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePurchaseOrder
     *
     * .
     *
     */
    public function testUpdatePurchaseOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePurchaseOrderStatus
     *
     * .
     *
     */
    public function testUpdatePurchaseOrderStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
