<?php
/**
 * SalesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orbit Public API
 *
 * The stable, external-integration surface of the Orbit API. Authenticate with an API key (Settings > API Keys) via the X-Api-Key header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KuziumOrbitClient\Test\Api;

use \KuziumOrbitClient\Configuration;
use \KuziumOrbitClient\ApiException;
use \KuziumOrbitClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SalesApiTest Class Doc Comment
 *
 * @category Class
 * @package  KuziumOrbitClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSalesOrder
     *
     * .
     *
     */
    public function testCreateSalesOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSalesOrder
     *
     * .
     *
     */
    public function testDeleteSalesOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSalesOrder
     *
     * .
     *
     */
    public function testGetSalesOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSalesOrders
     *
     * .
     *
     */
    public function testListSalesOrders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSalesOrder
     *
     * .
     *
     */
    public function testUpdateSalesOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSalesOrderStatus
     *
     * .
     *
     */
    public function testUpdateSalesOrderStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
